int levelBArray[][]={
  {TERRAIN, TERRAIN, NONE___, NONE___, NONE___, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN},
  {TERRAIN, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, TERRAIN},
  {TERRAIN, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, TERRAIN},
  {TERRAIN, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, TERRAIN},
  {TERRAIN, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, TERRAIN},
  {TERRAIN, NONE___, NONE___, PLATFRM, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, TERRAIN, NONE___, TERRAIN, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, TERRAIN},
  {TERRAIN, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, TERRAIN, NONE___, NONE___, NONE___, NONE___, NONE___, TERRAIN},
  {TERRAIN, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, TERRAIN, NONE___, NONE___, TERRAIN},
  {TERRAIN, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, TERRAIN},
  {TERRAIN, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, TERRAIN, TERRAIN},
  {TERRAIN, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, TERRAIN, TERRAIN, TERRAIN, TERRAIN},
  {TERRAIN, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, TERRAIN, TERRAIN, TERRAIN, NONE___, NONE___, NONE___, NONE___, TERRAIN, TERRAIN, TERRAIN, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, TERRAIN},
  {TERRAIN, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, TERRAIN},
  {TERRAIN, NONE___, NONE___, NONE___, TERRAIN, TERRAIN, TERRAIN, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, TERRAIN},
  {TERRAIN, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, NONE___, TERRAIN},
  {TERRAIN, TERRAIN, TRAPDOR, TRAPDOR, TRAPDOR, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN, TERRAIN},
};

level levelB;
